### ISSUE TITLE
Missing Shaders

### ISSUE THREAD

**Issue by jimbok8** [eliasnd/FastPoints#3]
In `PointCloudCamera`
you refer to `FilterPoints `and `FilteredPoints`, but both seem to be missing.
```
            computeShader = (ComputeShader)Resources.Load("FilterPoints");
            mat = new Material(Shader.Find("Custom/FilteredPoints"));
```
Is it possible you could supply these, please?
Thanks
Jim

**Comment by eliasnd** [comment]
Hi jim! Sorry, that was actually some dead code from experiments I was doing with compute shaders that didn't pan out. I wanted to implement something like [this](https://www.cg.tuwien.ac.at/research/publications/2021/SCHUETZ-2021-PCC/) method, but after messing around with it a bit found that I'd need to rework a lot of the unity rendering pipeline in the native plugin. I've removed the code in the newest commit
