### ISSUE TITLE
Unity crashed when finishing decimating point cloud

### ISSUE THREAD

**Issue by Orange-Ctrl** [eliasnd/FastPoints#4]
hi @eliasnd thanks for ur great work!
I built the project on Windows. 
I import a ply file. When decimating progress is 100%, Unity crashed. I wonder is  the project hasn't support Windows yet, or is my computer's hardware issues like VRAM?
I am totally new to this. It would be nice of you to answer my question.
Thanks!

**Comment by eliasnd** [comment]
Hi @Orange-Ctrl - I think this was an issue with how windows reloads the editor hierarchy and should be fixed. If you get a chance, let me know if it's working for you now!

**Comment by AbrarZShahriar** [comment]
I got the same issue, 2022.3. Using the latest code.

**Comment by AbrarZShahriar** [comment]
For small size (few hundred MBs) .ply  it works fine but for larger .ply files (few GBs) it crashes.
